samples/C#/mpgs-example-dotnet-all/Controllers/PaymentApiController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using gateway_csharp_sample_code.Models;
using Microsoft.Extensions.Options;
using gateway_csharp_sample_code.Gateway;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using gateway_csharp_sample_code.Utils;
using Microsoft.AspNetCore.WebUtilities;
using System.Text;
using System.Runtime.InteropServices;

namespace gateway_csharp_sample_code.Controllers

{
    /// <summary>
    /// Controller responsible to centralize the process and result methods
    /// </summary>
    public class PaymentApiController : BaseController
    {

        public PaymentApiController(IOptions<GatewayApiConfig> gatewayApiConfig, GatewayApiClient gatewayApiClient, NVPApiClient nvpApiClient, ILogger<PaymentApiController> logger) : 
        base (gatewayApiConfig, gatewayApiClient, nvpApiClient, logger)
        {
        }

        /// <summary>
        /// This method processes the API request for server-to-server operations. These are operations that would not commonly be invoked via a user interacting with the browser, but a system event (CAPTURE, REFUND, VOID).
        /// <summary>
        /// <param name="gatewayApiRequest">contains info on how to construct API call</param>
        /// <returns>IActionResult for api response page or error page</returns>
        [HttpPost("process"), HttpGet("process") ]
        public IActionResult Process(GatewayApiRequest gatewayApiRequest)
        {
            Logger.LogInformation($"PaymentApiController Process action gatewayApiRequest {JsonConvert.SerializeObject(gatewayApiRequest)}");

            gatewayApiRequest.GatewayApiConfig = GatewayApiConfig;

            //retrieve order doesnt require transaction information on the url
            if ("RETRIEVE_ORDER" == gatewayApiRequest.ApiOperation)
            {
                gatewayApiRequest.buildOrderUrl();
            }
            else
            {
                gatewayApiRequest.buildRequestUrl();
            }

            gatewayApiRequest.buildPayload();

            string response = GatewayApiClient.SendTransaction(gatewayApiRequest);

            buildViewData(gatewayApiRequest, response);

            return View(ViewList.GetValueOrDefault("ApiResponse"));
        }

        /// <summary>
        /// This method calls the INTIATE_BROWSER_PAYMENT operation, which returns a URL to the provider's website. The user is redirected to this URL, where the purchase is completed.
        /// </summary>
        /// <param name="gatewayApiRequest">contains info on how to construct API call</param>
        /// <returns>IActionResult for api response page or error page</returns>
        [HttpPost("processHostedSession")]
        public IActionResult ProcessHostedSession([FromBody] GatewayApiRequest gatewayApiRequest)
        {
            Logger.LogInformation($"PaymentApiController ProcessHostedSession action gatewayApiRequest {JsonConvert.SerializeObject(gatewayApiRequest)}");

            gatewayApiRequest.GatewayApiConfig = GatewayApiConfig;
            gatewayApiRequest.buildRequestUrl();
            gatewayApiRequest.buildPayload();

            string response = GatewayApiClient.SendTransaction(gatewayApiRequest);

            buildViewData(gatewayApiRequest, response);

            return View(ViewList.GetValueOrDefault("ApiResponse"));
        }

        [HttpPost("tokenize")]
        public IActionResult tokenize([FromBody] GatewayApiRequest gatewayApiRequest)
        {
            Logger.LogInformation($"PaymentApiController ProcessHostedSession action gatewayApiRequest {JsonConvert.SerializeObject(gatewayApiRequest)}");

            //update session with order details
            GatewayApiRequest gatewayUpdateSessionRequest = new GatewayApiRequest(GatewayApiConfig);
            gatewayUpdateSessionRequest.ApiMethod = GatewayApiClient.PUT;

            //update the url appending session id
            gatewayUpdateSessionRequest.buildSessionRequestUrl(gatewayApiRequest.SessionId);

            gatewayUpdateSessionRequest.OrderId = gatewayApiRequest.OrderId;
            gatewayUpdateSessionRequest.OrderCurrency = gatewayApiRequest.OrderCurrency;
            gatewayUpdateSessionRequest.OrderAmount = gatewayApiRequest.OrderAmount;

            //build payload with order info
            gatewayUpdateSessionRequest.buildPayload();

            String response = GatewayApiClient.SendTransaction(gatewayUpdateSessionRequest);

            Logger.LogInformation($"Tokenize updated session {response}");

            //validate transaction response
            if (JsonHelper.isErrorMessage(response))
            {
                return View("Error", ErrorViewModel.toErrorViewModel(getRequestId(), response));
            }

            //generate token
            GatewayApiRequest gatewayGenerateTokenRequest = new GatewayApiRequest(GatewayApiConfig);
            gatewayGenerateTokenRequest.SessionId = gatewayApiRequest.SessionId;
            gatewayGenerateTokenRequest.ApiMethod = GatewayApiClient.POST;
            gatewayGenerateTokenRequest.buildPayload();
            gatewayGenerateTokenRequest.buildTokenUrl();

            response = GatewayApiClient.SendTransaction(gatewayGenerateTokenRequest);

                //validate token response
                if (JsonHelper.isErrorMessage(response))
                {
                    return View("Error", ErrorViewModel.toErrorViewModel(getRequestId(), response));
                }

            //convert json to model
            TokenResponse tokenResponse = TokenResponse.ToTokenResponse(response);

            //payment with token
            GatewayApiRequest gatewayGeneratePaymentRequest = new GatewayApiRequest(GatewayApiConfig);
            gatewayGeneratePaymentRequest.ApiOperation = "PAY";
            gatewayGeneratePaymentRequest.ApiMethod = GatewayApiClient.PUT;

            gatewayGeneratePaymentRequest.Token = tokenResponse.Token;
            gatewayGeneratePaymentRequest.SessionId = gatewayApiRequest.SessionId;
            gatewayGeneratePaymentRequest.OrderId = gatewayApiRequest.OrderId;
            gatewayGeneratePaymentRequest.TransactionId = gatewayApiRequest.TransactionId;

            gatewayGeneratePaymentRequest.buildPayload();
            gatewayGeneratePaymentRequest.buildRequestUrl();

            response = GatewayApiClient.SendTransaction(gatewayGeneratePaymentRequest);

            buildViewData(gatewayGeneratePaymentRequest, response);

            return View(ViewList.GetValueOrDefault("ApiResponse"));
        }

        /// <summary>
        /// This method receives the callback from the Hosted Checkout redirect. It looks up the order using the RETRIEVE_ORDER operation and
        /// displays either the receipt or an error page.
        /// </summary>
        /// <param name="orderId">needed to retrieve order</param>
        /// <param name="result">Result of Hosted Checkout operation (success or error) - sent from hostedCheckout.html complete() callback</param>
        /// <returns>IActionResult for hosted checkout receipt page or error page</returns>
        [HttpGet("hostedCheckout/{orderId}/{result}"), HttpGet("hostedCheckout/{orderId}/{result}/{sessionId}")]
        public IActionResult HostedCheckoutReceipt([FromRoute(Name = "orderId")] string orderId, [FromRoute(Name = "result")] string result, [FromRoute(Name = "sessionId")] string sessionId)
        {
            Logger.LogInformation($"PaymentApiController HostedCheckoutReceipt action orderId {orderId} result {result} sessionId {sessionId}");

            if (result == "SUCCESS")
            {
                GatewayApiRequest gatewayApiRequest = new GatewayApiRequest(GatewayApiConfig)
                {
                    ApiOperation = "RETRIEVE_ORDER",
                    OrderId = orderId,
                    ApiMethod = GatewayApiClient.GET
                };

                gatewayApiRequest.buildOrderUrl();


                string response = GatewayApiClient.SendTransaction(gatewayApiRequest);

                Logger.LogInformation($"Hosted checkout retrieve order response {response}");

                //parse response
                TransactionResponseModel transactionResponseModel = null;
                try
                {
                    transactionResponseModel = TransactionResponseModel.toTransactionResponseModel(response);
                }
                catch (Exception e)
                {
                    Logger.LogError($"Hosted Checkout Receipt error : {JsonConvert.SerializeObject(e)}");

                    return View("Error", new ErrorViewModel
                    {
                        RequestId = getRequestId(),
                        Cause = e.InnerException != null ? e.InnerException.StackTrace : e.StackTrace,
                        Message = e.Message
                    });
                }

                return View(ViewList.GetValueOrDefault("Receipt"), transactionResponseModel);
            }
            else
            {
                Logger.LogError($"The payment was unsuccessful {result}");
                return View("Error", new ErrorViewModel
                {
                    RequestId = getRequestId(),
                    Cause = "Payment was unsuccessful",
                    Message = "There was a problem completing your transaction."
                });
            }
        }

        /// <summary>
        /// This method handles the response from the CHECK_3DS_ENROLLMENT operation. If the card is enrolled, the response includes the HTML for the issuer's authentication form, to be injected into secureIdPayerAuthenticationForm.html.
        /// Otherwise, it displays an error.
        /// <summary> 

samples/C#/mpgs-example-dotnet-all/Views/Payment/ApiResponse.cshtml
<div class="col-9 pl-4">
    <h3>@ViewBag.Operation Operation</h3>
    <p class="endpoint">@ViewBag.Method @ViewBag.RequestUrl</p>

    <h5>Payload</h5>
    <pre>@ViewBag.Payload</pre>

    <h5>Response</h5>
    <pre>@ViewBag.Response</pre>
</div>

samples/C#/mpgs-example-dotnet-all/Views/Payment/Authorize.cshtml
@using gateway_csharp_sample_code.Gateway
@model gateway_csharp_sample_code.Gateway.GatewayApiRequest

<script type="text/javascript">
    var DotNetSample = {
        operation: function() {
            return "AUTHORIZE";
        },
        endpoint: function() {
            return "/processHostedSession/";
        },
        secureIdResponseUrl: function() {
            return null;
        }
    };
</script>
<!-- APPLY CLICK-JACKING STYLING AND HIDE CONTENTS OF THE PAGE -->
<style id="antiClickjack">body{display:none !important;}</style>
<!-- INCLUDE SESSION.JS JAVASCRIPT LIBRARY -->
<script src="@ViewBag.JavascriptSessionUrl"></script>
<div class="col-9">
    <div class="row">
        <div class="contents col-12">
            <div class="col-md-12">
                <h3>Authorize</h3>
                <div class="alert alert-warning" role="alert">
                    <p class="mb-0">In order to run the Authorize API operation, please make sure the merchant is configured to "Authorize and Capture" payment mode.</p>
                    <p>You can find test cards <a href="@ViewBag.TestAndGoLiveUrl">here</a>.</p>                    
                </div>
                <div id="error-alert" class="alert alert-danger" role="alert">
                    <p>The following error(s) occurred:</p>
                </div>
                <div class="mb-4">
                    <h6>Payment details</h6>
                    <div class="form-group">
                        <label for='card-number'>Card number:</label>
                        <input type="text" id="card-number" class="form-control input-md" readonly required>
                    </div>
                    <div class="form-group">
                        <label for='expiry-month'>Expiry month:</label>
                        <input asp-for="ExpiryMonth" type="text" id="expiry-month" maxlength="2" class="form-control input-md" required>
                    </div>
                    <div class="form-group">
                        <label for='expiry-year'>Expiry year:</label>
                        <input asp-for="ExpiryYear" type="text" id="expiry-year" maxlength="4" class="form-control input-md" required>
                    </div>
                    <div class="form-group">
                        <label for='security-code'>Security code:</label>
                        <input type="text" id="security-code" class="form-control input-md" readonly required>
                    </div>
                </div>
                <div>
                    <h6>Order details</h6>
                    <div class="form-group">
                        <label for='order-id'>Order ID:</label>
                        <input asp-for="OrderId" type="text" id="order-id" class="form-control input-md">
                    </div>
                    <div class="form-group">
                        <label for='order-amount'>Order amount:</label>
                        <input asp-for="OrderAmount" type="text" id="order-amount" class="form-control input-md" maxlength="14">
                    </div>
                    <div class="form-group">
                        <label for='order-currency'>Order currency:</label>
                        <input asp-for="OrderCurrency" type="text" id="order-currency" class="form-control input-md" maxlength="3">
                    </div>
                    <div class="form-group">
                        <label for='order-description'>Description:</label>
                        <input asp-for="OrderDescription" type="text" id="order-description" class="form-control input-md" maxlength="127">
                    </div>
                    <div class="form-group">
                        <label for='transaction-id'>Transaction ID:</label>
                        <input asp-for="TransactionId" type="text" id="transaction-id" class="form-control input-md">
                    </div>
                </div>
                <button type="submit" class="mt-4 btn btn-primary" id="payButton" onclick="pay();">Authorize</button>
            </div>
        </div>
    </div> <!-- row -->
</div>
<script src="/js/hostedSession.js"></script>

samples/C#/mpgs-example-dotnet-all/Views/Payment/Capture.cshtml
@using gateway_csharp_sample_code.Gateway
@model gateway_csharp_sample_code.Gateway.GatewayApiRequest

<div class="col-9">
    <div class="row">
        <form class="col-12 form-horizontal" asp-controller="PaymentApi" asp-action="process" method="post">
            <h3>Capture</h3>
            <div class="alert alert-warning" role="alert">
                This API operation is typically not a browser initiated action. However, we are calling this action from browser only as a reference to get an idea of how it can be done through your application.
            </div>
            <div class="mb-4">
                <input asp-for="TransactionId" id="transactionId" type="hidden" />
                <input asp-for="ApiOperation" id="apiOperation" type="hidden" />
                <input asp-for="ApiMethod" id="apiMethod" type="hidden" />
                <div class="form-group">
                    <label for="order-id">Order ID</label>
                     <input asp-for="OrderId" id="order-id" type="text" placeholder="[Order ID from existing authorization]" class="form-control input-md" required=""/>
                </div>
                <div class="form-group">
                    <label for="transaction-amount">Amount</label>
                    <input asp-for="TransactionAmount" id="transaction-amount" type="text" placeholder="[Amount less than or equal to the authorized amount]" class="form-control input-md" required=""/>                      
                </div>
                <div class="form-group">
                    <label for="transaction-currency">Currency</label>
                    <input asp-for="TransactionCurrency" id="transaction-currency" type="text" placeholder="[Currency from existing authorization]" class="form-control input-md" required=""/>
                </div>
                <div class="form-group">
                    <button id="process" name="process" class="btn btn-primary">Process Capture</button>
                </div>
            </div>
        </form>
    </div> <!-- row -->
</div>

samples/C#/mpgs-example-dotnet-all/Views/Payment/PayWithMasterpass.cshtml
@using gateway_csharp_sample_code.Gateway
@model gateway_csharp_sample_code.Gateway.GatewayApiRequest

@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@addTagHelper *, AuthoringTagHelpers

<script type="text/javascript">
    var DotNetSample = {
        operation: function() {
            return "MASTERPASS";
        },
        endpoint: function() {
            return "/processMasterpass";
        },
        secureIdResponseUrl: function() {
            return null;
        }
    };
</script>
<!-- APPLY CLICK-JACKING STYLING AND HIDE CONTENTS OF THE PAGE -->
<style id="antiClickjack">body{display:none !important;}</style>
<!-- INCLUDE SESSION.JS JAVASCRIPT LIBRARY -->
<script src="@ViewBag.JavascriptSessionUrl"></script>

@using(Html.BeginForm("processMasterpass", "PaymentApi", FormMethod.Post, new {@class="col-9 form-horizontal"})){
        <div class="row">
            <div class="contents col-12">
                <div class="col-md-12">
                    <h3>Pay with Masterpass</h3>
                    <div class="alert alert-warning" role="alert">
                        <p><strong>NOTE:</strong> You can also do an authorization via Masterpass, depending on your merchant settings.</p>
                        <p>This page is for demonstration purposes only, to collect information like order amount and currency in order to generate the Masterpass button. In practical use this would be collected behind the scenes.</p>
                        <p>Here are the steps to complete this transaction:</p>
                        <ol>
                            <li>Use the <a href="@ViewBag.MasterpassCreateSession" target="_blank">CREATE_SESSION</a> operation to create a session.</li>
                            <li>Use the <a href="@ViewBag.MasterpassOpenWallet" target="_blank">UPDATE_SESSION</a> operation to update the session with information about the order (like amount, description, currency, etc).</li>
                            <li>Use the <a href="@ViewBag.MasterpassJSLibrary" target="_blank">OPEN_WALLET</a> operation to initiate the Masterpass interaction.</li>
                            <li>Use the <a href="@ViewBag.MasterpassUpdateSessionFromWallet" target="_blank">Masterpass JavaScript library</a> to launch the Masterpass interaction.</li>
                            <li>Use the URL parameters included in the Masterpass callback with the <a href="@ViewBag.MasterpassPay" target="_blank">UPDATE_SESSION_FROM_WALLET</a> operation to retrieve the payment details from Masterpass. </li>
                            <li>Use the payment details to complete the transaction using <a href="@ViewBag.MasterpassAuthorize" target="_blank">AUTHORIZE</a>.</li>
                        </ol>
                        <p>View the full Masterpass documentation <a href="@ViewBag.MasterpassFullDocumentation" target="_blank">here</a>.</p>
                    </div>              
                    <div>
                    <div class="form-group">
                            <label for="wallet-provider">Wallet Provider</label>
                            <input id="wallet-provider" asp-for="MasterpassOnline" type="text" placeholder="" class="form-control input-md" readonly >
                        </div>
                    <div class="form-group">
                            <label for="origin-url">Origin URL (where Masterpass will redirect after transaction is complete)</label>
                            <input id="origin-url" asp-for="MasterpassOriginUrl" type="text" placeholder="" class="form-control input-md" readonly >
                        </div>                    
                    <div class="form-group">
                            <label for='order-id'>Order ID:</label>
                            <input asp-for="OrderId" type="text" id="order-id" class="form-control input-md">
                        </div>
                    <div class="form-group">
                            <label for='order-amount'>Order amount:</label>
                            <input asp-for="OrderAmount" type="text" id="order-amount" class="form-control input-md" maxlength="14">
                        </div>
                    <div class="form-group">
                            <label for='order-currency'>Order currency:</label>
                            <input asp-for="OrderCurrency" type="text" id="order-currency" class="form-control input-md" maxlength="3">
                        </div>
                    </div>
                    <button type="submit" class="mt-4 btn btn-primary" id="payButton">Generate Masterpass button</button>
                </div>
            </div>
        </div>
}
<script src="/js/hostedSession.js"></script>

samples/C#/mpgs-example-dotnet-all/Views/Payment/PayWithPayPal.cshtml
@using gateway_csharp_sample_code.Gateway
@model gateway_csharp_sample_code.Gateway.GatewayApiRequest

@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@addTagHelper *, AuthoringTagHelpers


<script type="text/javascript">
    var DotNetSample = {
        operation: function() {
            return "INITIATE_BROWSER_PAYMENT";
        },
        endpoint: function() {
            return "processPaymentWithPayPal";
        },
        secureIdResponseUrl: function() {
            return null;
        }
    };
</script>
<!-- APPLY CLICK-JACKING STYLING AND HIDE CONTENTS OF THE PAGE -->
<style id="antiClickjack">body{display:none !important;}</style>
<!-- INCLUDE SESSION.JS JAVASCRIPT LIBRARY -->
<script src="@ViewBag.JavascriptSessionUrl"></script>

@using(Html.BeginForm("processPaymentWithPayPal", "PaymentApi", FormMethod.Post, new {@class="col-9 form-horizontal"})){
            <div class="contents col-12">
                <div class="col-md-12">
                    <h3>Pay with PayPal</h3>
                    <div class="alert alert-warning" role="alert">
                        <p>
                            <strong>NOTE:</strong> You can also do an authorization via PayPal, 
                            depending on your merchant settings.
                        </p>
                        <p> 
                            You can access full integration guidelines 
                            <a href="@ViewBag.DocumentationPayPal" target="_blank"> here</a>. 
                        <p/>
                    </div>                
                    <div class="mb-4" >
                        <h6>Order details</h6>
                    <div class="form-group">
                            <label for='order-id'>Order ID:</label>
                            <input asp-for="OrderId" type="text" id="order-id" class="form-control input-md">
                        </div>
                    <div class="form-group">
                            <label for='order-amount'>Order amount:</label>
                            <input asp-for="OrderAmount" type="text" id="order-amount" class="form-control input-md" maxlength="14">
                        </div>
                    <div class="form-group">
                            <label for='order-currency'>Order currency:</label>
                            <input asp-for="OrderCurrency" type="text" id="order-currency" class="form-control input-md" maxlength="3">
                        </div>
                    <div class="form-group">
                            <label for='order-description'>Description:</label>
                            <input asp-for="OrderDescription" type="text" id="order-description" class="form-control input-md" maxlength="127">
                        </div>
                    <div class="form-group">
                            <label for='transaction-id'>Transaction ID:</label>
                            <input asp-for="TransactionId" type="text" id="transaction-id" class="form-control input-md">
                        </div>
                    </div>
                    <button type="submit" class="mt-4 btn btn-primary" id="payButton">Pay with PayPal</button>
                </div>
            </div>
}
<script src="/js/hostedSession.js"></script>

samples/C#/mpgs-example-dotnet-all/Views/Payment/Receipt.cshtml
<div class="col-9 pl-4">
    <h3>Payment complete!</h3>
    <div>Your payment was @Model.GatewayCode</div>
    <div class="container mt-4 ml-0">
        <div class="row">
            <div class="col">
                Order ID
            </div>
            <div class="col">
                <p>@Model.OrderId</p>
            </div>
        </div>
        @if (!String.IsNullOrEmpty(Model.OrderDescription))
        {
            <div class="row">
                <div class="col">
                    Description
                </div>
                <div class="col">
                    <p>@Model.OrderDescription</p>
                </div>
            </div>
        }
        <div class="row">
            <div class="col">
                Amount
            </div>
            <div class="col">
                <p>@Model.OrderAmount @Model.OrderCurrency</p>
            </div>
        </div>
    </div>
</div>

samples/C#/mpgs-example-dotnet-all/Views/Payment/Refund.cshtml
@using gateway_csharp_sample_code.Gateway
@model gateway_csharp_sample_code.Gateway.GatewayApiRequest

<div class="col-9">
    <div class="row">
        <form class="col-12 form-horizontal" asp-controller="PaymentApi" asp-action="process" method="post">
            <h3>Refund</h3>
            <div class="alert alert-warning" role="alert">
                This API operation is typically not a browser initiated action. However, we are calling this action from browser only as a reference to get an idea of how it can be done through your application.
            </div>
            <fieldset>
                <input asp-for="TransactionId" id="transactionId" type="hidden" />
                <input asp-for="ApiOperation" id="apiOperation" type="hidden" />
                <input asp-for="ApiMethod" id="apiMethod" type="hidden" />
                <div class="form-group">
                    <label  for="order-id">Order ID</label>
                    <input asp-for="OrderId" id="order-id" type="text" placeholder="[Order ID for existing order]" class="form-control input-md" required=""/>
                </div>
                <div class="form-group">
                    <label  for="transaction-amount">Amount</label>
                    <input asp-for="TransactionAmount" id="transaction-amount" type="text" placeholder="[Amount less than or equal to the transaction amount]" class="form-control input-md" required=""/>                      
                </div>
                <div class="form-group">
                    <label for="transaction-currency">Currency</label>
                    <input asp-for="TransactionCurrency" id="transaction-currency" type="text" placeholder="[Currency from existing order]" class="form-control input-md" required=""/>
                </div>
                <div class="form-group">
                    <button id="process" name="process" class="btn btn-primary">Process Refund</button>
                </div>
            </fieldset>
        </form>
    </div> 
</div>

samples/C#/mpgs-example-dotnet-all/Views/Payment/RetrieveOrder.cshtml
@using gateway_csharp_sample_code.Gateway
@model gateway_csharp_sample_code.Gateway.GatewayApiRequest

<div class="col-9">
    <div class="row">
        <form class="col-12 form-horizontal" asp-controller="PaymentApi" asp-action="process" method="post">
            <h3>Retrieve Order</h3>
            <div class="alert alert-warning" role="alert">
                <p>A valid order ID are needed to retrieve a order.</p>
                <p>To get these values, run the Pay process, then enter the values from the response.</p>
            </div>
            <fieldset>
                <input asp-for="ApiOperation" type="hidden" />
                <input asp-for="ApiMethod" type="hidden" />
                <div class="form-group">
                    <label for="order-id">Order ID</label>
                    <input asp-for="OrderId" id="order-id" type="text" placeholder="[Order ID from existing transaction]" class="form-control input-md" required=""/>
                </div>
                <div class="form-group">
                    <button id="process" name="process" class="btn btn-primary">Retrieve Transaction</button>
                </div>
            </fieldset>
        </form>
    </div> 
</div>

samples/C#/mpgs-example-dotnet-all/Views/Payment/Void.cshtml
@using gateway_csharp_sample_code.Gateway
@model gateway_csharp_sample_code.Gateway.GatewayApiRequest

<div class="col-9">
    <div class="row">
        <form class="col-12 form-horizontal" asp-controller="PaymentApi" asp-action="process" method="post">
            <h3>Void</h3>
            <div class="alert alert-warning" role="alert">
                This API operation is typically not a browser initiated action. However, we are calling this action from browser only as a reference to get an idea of how it can be done through your application.
            </div>
            <fieldset>
                <input asp-for="TransactionId" id="transactionId" type="hidden" />
                <input asp-for="ApiOperation" id="apiOperation" type="hidden" />
                <input asp-for="ApiMethod" id="apiMethod" type="hidden" />
                <div class="form-group">
                    <label for="order-id">Order ID</label>
                        <input asp-for="OrderId" id="order-id" type="text" placeholder="[Order ID from existing transaction]" class="form-control input-md" required=""/>
                </div>
                <div class="form-group">
                    <label for="target-transaction-id">Target Transaction ID</label>
                        <input asp-for="TargetTransactionId" id="target-transaction-id" type="text" placeholder="[Transaction ID from existing transaction]" class="form-control input-md" required=""/>
                </div>
                <div class="form-group">
                   <button id="process" name="process" class="btn btn-primary">Process Void</button>
                </div>
            </fieldset>
        </form>
    </div> <!-- row -->
</div>